### PR TITLE
chore: unify license header checks

### PR DESCRIPTION
**Pull request by tisonkun**
This closes https://github.com/CeresDB/horaedb/issues/1339.

@ananta I found your comment later this patch was made, you can join in the review instead >_<

### CODE REVIEW

**Comment by ananta** [comment]
> This closes #1339.
> 
> @ananta I found your comment later this patch was made, you can join in the review instead >_<

Hehe you're good 😄 . Thanks for the contribution! 🚀

**Comment by tanruixiang** [comment]
Make sense to me. The original way also will format. @ShiKaiWi @jiacai2050 Should be using git hooks a lot. Do you accept this dependency on docker?

**Comment by tisonkun** [comment]
> The original way also will format

Then we can change `check` to `format`.

**Comment by jiacai2050** [comment]
I don't like this change very much...
1. This hook will be invoked on every commit, run docker is more heavier than a simple python script.
2. docker has poor performance on mac, and user may don't even have docker installed at all.

So I suggest we adopt a simple way to do this task.

**Pull request closed without merging**
